import React from "react";
import Footer from "../../components/footer";
import Navbar from "../../components/navbar";
import { getDictionary } from "../dictionaries";

export default async function PrivacyPolicy({
  params: { lang },
}: {
  params: { lang: "en" | "ti" };
}) {
  const dict = await getDictionary(lang);
  return (
    <>
      <Navbar
        navLight={false}
        playBtn={true}
        bgLight={false}
        navCenter={true}
        language={false}
      />

      <section className="relative md:py-24 py-16">
        <div className="container relative">
          <div className="md:flex justify-center">
            <div className="max-w-3xl">
              <div className="p-6 ">
                <h5 className="text-xl font-bold mb-4">Privacy Policy</h5>
                <p className=" mb-4">
                  <span className="font-semibold">Last updated:</span> October
                  19, 2024
                </p>

                <div className="">
                  <p className="mb-4">
                    This Privacy Policy outlines our policies and procedures
                    regarding the collection, use, and disclosure of your
                    information when you use our services. It also informs you
                    of your privacy rights and how legal protections apply to
                    you.
                  </p>

                  <p className="mb-6">
                    We use your personal data to deliver and enhance our
                    services. By utilizing our services, you agree to the
                    collection and use of information as described in this
                    Privacy Policy.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Interpretation and Definitions
                  </h6>
                  <h6 className="font-semibold mb-2">Interpretation</h6>
                  <p className="mb-4">
                    Words with the first letter capitalized have specific
                    meanings under the conditions defined below. The definitions
                    will apply regardless of whether the words are in singular
                    or plural form.
                  </p>

                  <h6 className="font-semibold mb-2">Definitions</h6>
                  <p className="mb-4">
                    For the purposes of this Privacy Policy:
                  </p>
                  <ul className="list-disc pl-6 mb-6 space-y-2">
                    <li>
                      <strong>Account:</strong> A unique account created for you
                      to access our services or parts of our services.
                    </li>
                    <li>
                      <strong>Affiliate:</strong> Any entity that controls, is
                      controlled by, or is under common control with a party,
                      where “control” means the ownership of 50% or more of the
                      shares, equity interest, or other securities entitled to
                      vote for directors or other managing authority.
                    </li>
                    <li>
                      <strong>Application:</strong> Refers to AdoPay Digital
                      Landing, the software provided by the Company.
                    </li>
                    <li>
                      <strong>Company</strong> (referred to as either "the
                      Company," "We," "Us," or "Our" in this Agreement): Refers
                      to Dedebit Microfinance Institutions, Mekelle, Tigray,
                      Ethiopia.
                    </li>
                    <li>
                      <strong>Country:</strong> Refers to Ethiopia.
                    </li>
                    <li>
                      <strong>Device:</strong> Any device capable of accessing
                      the service, such as a computer, cellphone, or digital
                      tablet.
                    </li>
                    <li>
                      <strong>Personal Data:</strong> Information that relates
                      to an identified or identifiable individual.
                    </li>
                    <li>
                      <strong>Service:</strong> Refers to the Application.
                    </li>
                    <li>
                      <strong>Service Provider:</strong> Any natural or legal
                      person who processes data on behalf of the Company. These
                      third parties assist in facilitating the service,
                      providing the service, or analyzing its use.
                    </li>
                    <li>
                      <strong>Usage Data:</strong> Data collected automatically,
                      generated by the service's usage or the service
                      infrastructure itself (e.g., duration of page visits).
                    </li>
                    <li>
                      <strong>You:</strong> The individual using the service or
                      the company/legal entity on whose behalf the individual is
                      accessing the service.
                    </li>
                  </ul>

                  <h6 className="text-lg font-semibold mb-3">
                    Collecting and Using Your Personal Data
                  </h6>
                  <h6 className="font-semibold mb-2">
                    Types of Data Collected
                  </h6>
                  <ul className="list-disc pl-6 mb-6 space-y-2">
                    <li>
                      <strong>Personal Data:</strong> We may request personally
                      identifiable information, including but not limited to:
                      <ul className="list-circle pl-6 mt-2 space-y-1">
                        <li className="flex ">
                          <span className="mr-2">○</span> First Name, Middle
                          Name, Last Name
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Gender
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Birth Date
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Marital Status
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Personal Address,
                          Region, City, Zone/Sub-City, Woreda, House Number
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Type of ID and ID
                          Number
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Tax Identification
                          Number (TIN)
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Account Number
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Business Sector and
                          Line of Business
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Other business and
                          financial information, such as Annual Sales, Starting
                          Capital, Annual Profit, etc.
                        </li>
                      </ul>
                    </li>
                    <li>
                      <strong>Usage Data:</strong> Automatically collected
                      information when using the service, such as the type of
                      device used, IP address, browser type, unique device
                      identifiers, and other diagnostic data.
                    </li>
                    <li>
                      <strong>
                        Information Collected while Using the Application:
                      </strong>{" "}
                      With your permission, we may collect:
                      <ul className="list-circle pl-6 mt-2 space-y-1">
                        <li className="flex ">
                          <span className="mr-2">○</span> Location data
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Phone book contacts
                        </li>
                        <li className="flex ">
                          <span className="mr-2">○</span> Photos and media files
                        </li>
                      </ul>
                      You can enable or disable access to these features through
                      your device settings.
                    </li>
                  </ul>

                  <h6 className="text-lg font-semibold mb-3">
                    Use of Your Personal Data
                  </h6>
                  <p className="mb-4">
                    The Company may use your Personal Data for various purposes,
                    including but not limited to:
                  </p>
                  <ul className="list-disc pl-6 mb-6 space-y-2">
                    <li>Providing and maintaining the service</li>
                    <li>Managing your account</li>
                    <li>Fulfilling contractual obligations</li>
                    <li>
                      Contacting you regarding updates, promotions, or
                      service-related information
                    </li>
                    <li>Managing your requests and inquiries</li>
                    <li>Analyzing and improving our services</li>
                    <li>
                      Legal purposes, such as mergers or compliance with law
                      enforcement
                    </li>
                  </ul>

                  <h6 className="text-lg font-semibold mb-3">
                    Retention of Your Personal Data
                  </h6>
                  <p className="mb-6">
                    We will retain your Personal Data for as long as necessary
                    to fulfill the purposes outlined in this policy. Retention
                    may be extended to comply with legal obligations or to
                    resolve disputes.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Transfer of Your Personal Data
                  </h6>
                  <p className="mb-6">
                    Your data may be processed at the Company's operational
                    offices or transferred to other locations where service
                    providers are based. By using the service, you agree to the
                    transfer of your data in compliance with applicable security
                    protocols.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Disclosure of Your Personal Data
                  </h6>
                  <ul className="list-disc pl-6 mb-6 space-y-2">
                    <li>
                      <strong>Business Transactions:</strong> If the Company is
                      involved in a merger, acquisition, or sale, your data may
                      be transferred.
                    </li>
                    <li>
                      <strong>Law Enforcement:</strong> We may disclose your
                      data if required by law.
                    </li>
                    <li>
                      <strong>Other Legal Requirements:</strong> Data may be
                      disclosed to protect our legal rights, investigate
                      wrongdoing, or safeguard users.
                    </li>
                  </ul>

                  <h6 className="text-lg font-semibold mb-3">
                    Security of Your Personal Data
                  </h6>
                  <p className="mb-6">
                    We take the security of your data seriously and use
                    commercially acceptable methods to protect it. However, no
                    method of transmission or storage is completely secure, and
                    we cannot guarantee absolute protection.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Children's Privacy
                  </h6>
                  <p className="mb-6">
                    Our services are not intended for individuals under the age
                    of 18. If we become aware that we have collected personal
                    data from individuals under 18, we will take steps to delete
                    it.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Links to Other Websites
                  </h6>
                  <p className="mb-6">
                    Our service may contain links to third-party websites. We do
                    not control or assume responsibility for the privacy
                    policies or content of these websites.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">
                    Changes to this Privacy Policy
                  </h6>
                  <p className="mb-6">
                    We may update this policy periodically. You will be notified
                    of significant changes via email or through a notice on our
                    service. The updated policy will be effective once posted.
                  </p>

                  <h6 className="text-lg font-semibold mb-3">Contact Us</h6>
                  <p className="mb-4">
                    For any questions about this Privacy Policy, please contact
                    us at:
                  </p>
                  <ul className="list-none mb-6">
                    <li>Phone: +251 924793826 </li>
                    <li>Email: help@decsimfi.com</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
